package com.ikouz.algorithm.leetcode;

/**
 * @author liujiaming
 * @since 2017/03/25
 */
public class Bit_389_FindtheDifference {

    /**
     * Given two strings s and t which consist of only lowercase letters.
     * <p>
     * String t is generated by random shuffling string s and then add one more letter at a random position.
     * <p>
     * Find the letter that was added in t.
     * <p>
     * Example:
     * Input:
     * s = "abcd"
     * t = "abcde"
     * Output:
     * e
     * Explanation:
     * 'e' is the letter that was added.
     *
     * @param s
     * @param t
     * @return
     */
    public static char findTheDifference(String s, String t) {
        if (s == null) {
            return 0;
        }
        char[] arrS = s.toCharArray();
        char[] arrT = t.toCharArray();
        int[] map = new int[26];
        for (int i = 0; i < arrS.length; i++) {
            map[arrS[i] - 'a'] += 1;
        }
        for (int i = 0; i < arrT.length; i++) {
            map[arrT[i] - 'a'] -= 1;
        }
        for (int i = 0; i < map.length; i++) {
            if (map[i] != 0) {
                return (char) (i + 'a');
            }
        }
        return 0;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("a", "aa"));
    }
}
